name = "TauPy"
uuid = "fa53487c-c63f-11e8-170c-e7abdb8d2806"
authors = ["Andy Nowacki <a.nowacki@leeds.ac.uk>"]
version = "0.3.3"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
PyCall = "1.90, 2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
